server:
  port: ${SERVER_PORT_COURSE}
  servlet:
    context-path: '/ead-course/'
  
spring:
  application:
    name: ead-course-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
            
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL_COURSE}
    username: ${POSTGRE_USERNAME_COURSE}
    password: ${POSTGRE_PASSWORD_COURSE}
      
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update 
  
  rabbitmq:
    addresses: amqps://ifbfuizl:YinG-5yJAQDmEjWvNYL8HaVxZZLYvnwS@hawk.rmq.cloudamqp.com/ifbfuizl
            
#Configuração para windows terminal padrao de cores            
  output:
    ansi:
      enabled: always

logging:
  level:
    '[com.ead]': trace
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info      

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
      notificationCommandExchange: ead.notificationcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification             

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
        
      