
server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: admin
    password: PO_postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hobernate.dialect.PostgreSQLDialect
    jdbc: 
        lob.non-contextual-creation: true
        type:
          descriptor:
            sql:trace
      
