server:
  port: ${SERVER_PORT_NOTIFICATION}
  servlet:
    context-path: '/ead-notification-hex/'
  
spring:
  application:
    name: ead-notification-service-hex
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server  
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
            
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL_NOTIFICATION}/ead-notification-hex
    username: ${POSTGRE_USERNAME_NOTIFICATION}
    password: ${POSTGRE_PASSWORD_NOTIFICATION}
      
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update 
  
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}
            
#Configura��o para windows terminal padrao de cores            
  output:
    ansi:
      enabled: always

logging:
  level:
    '[com.ead]': trace
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info      

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification
  auth:
    jwtSecret: XL2bRh34SCmnOEfQB5Dh4YDiFmCUvYpis4H79RSm1Oq7HsjhwFSlyJHPAgMaoEwXdbY2SAHpnR8xdxbSbOapsCTcOlir3zhErnIGa1Lt4EFtvKYXLPRJpZ8gSmc4JSMOAOQvmpNUnfgklKEqXLH6gofevJi3xlEcKQRXkIZROGTQn9uXBdcmTUXXWO4YSTjJalcbsp63BX1IgdgJ4igyajugiwVCpDOELGEusx0HN5VOOnkRA1at63ZalGFhwlyiDhPk3AG1Wgh7AmXfVsBDt36hAha34BUOKeRbxA0QY30UhHQsPIXormGhRfmM3tWr8QKv6VIWmjJwXslx1iEcf46mihJGxfzWnFKGnmFa6vUT53KiclUFY9haKvOiVmqNdkHqGNybSHYSoqh9FOWPmNP5oTGrCcEEV4jOVI5UOtaNLx4yQ4eV2ntUpKaanMHJ63JSnRZrDlOQHQaHkKIUuoEKsodDAHz7m89Kh39DJ7kKQwPtAXCB3rJo4pJKE7gO
    jwtExpirationMs: 14400000
  serviceRegistry:
    username: ${SERVICE_REGISTRY_USERNAME}
    password: ${SERVICE_REGISTRY_PASSWORD}    
    
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
      #defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost         
    