server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ead-config-server
#  profiles:
#    active: develop
  cloud:
    config:
      server:
        git:
          uri: https://github.com/augustczar/eadconfigserverrepo
          default-label: develop
          username: ${USER_NAME}
          password: ${ACCESS_TOKEN_GIT}
          
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost    
    