server:
  port: ${SERVER_PORT_AUTHUSER}
  servlet:
    context-path: '/ead-authuser/'
  
spring:
  application:
    name: ead-authuser-service
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL_AUTHUSER}
    username: ${POSTGRE_USERNAME_AUTHUSER}
    password: ${POSTGRE_PASSWORD_AUTHUSER}
  
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: amqps://ifbfuizl:YinG-5yJAQDmEjWvNYL8HaVxZZLYvnwS@hawk.rmq.cloudamqp.com/ifbfuizl

#Configuração para windows terminal padrao de cores            
  output:
    ansi:
      enabled: always

logging:
  level:
    '[com.ead]': trace
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate]': info
    
ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 80 
  retry:
    instances:
      retryInstance:
        maxAttempts: 3
        waitDuration: 5s        
      